### ISSUE TITLE
Unable to catch ECONNRESET error and it is causing app to crash.

### ISSUE THREAD

**Issue by daveteu** [socketio/socket.io-redis-adapter#412]
I need some help as your documentation on Client Error handling seems to be gone.

I've searched through forums and issues here. I've followed the recommended actions as follows. **However**, I'm still not able to catch the errors below, and it's causing my app to crash. My redis servers are all well and not disconnected at that time as I have other services using same server.

Can anyone provide me with some directions?

>  "@socket.io/redis-adapter": "^7.0.0",
>   "@socket.io/redis-emitter": "^4.1.0",

**Catching error for both sub and pub client  - Done ✅**
```
pubClient.on("error", (err) => {
	debug(`REDIS ADAPTOR DISCONNECTED ON pubClient %O`, err)
})
subClient.on("error", (err) => {
	debug(`REDIS ADAPTOR DISCONNECTED ON subClient %O`, err)
})
```

**Catch error on adapter - Done ✅**

```
io.of('/').adapter.on('error', function(error){

	debug('error: ', error);
	
});
```

**Ping to keep connection alive - Done ✅**

```
setInterval(() => {
	// emitter.of('/user').emit("time", new Date);
	io.of('/user').emit("time", new Date())
  }, 300000);
```

**I've also tried using both node-redis and ioredis and both end up with same error below Done ✅**

## Manage to catch this with redis on error event ✅
```
 socket REDIS ADAPTOR DISCONNECTED ON pubClient Error: read ECONNRESET
  socket     at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  socket   errno: -54,
  socket   code: 'ECONNRESET',
  socket   syscall: 'read'
  socket } +5h
  socket error:  Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
} +0ms
```

# Unable to catch this event ❌❌❌
I think this causes my app to crash
```

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on RedisAdapter instance at:
    at Redis.onError (/Users/Myname/Work/expressjs/api.singa.sg/node_modules/@socket.io/redis-adapter/dist/index.js:61:22)
    at Redis.emit (events.js:327:22)
    at Redis.EventEmitter.emit (domain.js:486:12)
    at Redis.silentEmit (/Users/Myname/Work/expressjs/api.singa.sg/node_modules/ioredis/built/redis/index.js:544:26)
    at Socket.<anonymous> (/Users/Myname/Work/expressjs/api.singa.sg/node_modules/ioredis/built/redis/event_handler.js:190:14)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by vincesempre** [comment]
Hi!
I had a similar issue and I resolved it by adding an error listener on each namespace.

Something like:

``` js
const namespaces = io.nsps;
Object.keys(namespaces).forEach((namespaceName) => {
  io.of(namespaceName).adapter.on('error', (e) => {
  console.error(`On namespace: ${namespaceName} - ${e}`);
  });
});
```
Hope this helps!
M.

**Comment by daveteu** [comment]
> Hi!
> I had a similar issue and I resolved it by adding an error listener on each namespace.
> 
> Something like:
> 
> ```js
> const namespaces = io.nsps;
> Object.keys(namespaces).forEach((namespaceName) => {
>   io.of(namespaceName).adapter.on('error', (e) => {
>   console.error(`On namespace: ${namespaceName} - ${e}`);
>   });
> });
> ```
> 
> Hope this helps!
> M.

Thank you but why is my io.nsps undefined?

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/8e5c84f7edcda85a6f7e36c04ebd74152c1cade1, included in release 7.1.0: https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.1.0

**Comment by gollobo** [comment]
Hello, I'm still experiencing the same issue. I've tried with various Redis hosts in case that was the problem. I've also tried using both redis-node and ioredis, but it doesn't seem to work either. I've tried with TLS and without TLS. I'm a bit desperate because the error randomly restarts my Node.js server a couple of times a day. I've tried the following solutions:

Catch the error with:
```
pubClient.on("error", function(err){ console.log(err)});
```

```
server.listen(process.env.PORT || 3000, () => {
 //logic here
}).on('error', function (err) {
    console.log(err);
});
```

```
process.on('uncaughtException', function (err) {
    console.log(err.stack)
});
```

```
io.of('/').adapter.on('error', function (error) {
  console.log('error: ', error);
});
```

None of these solutions catch the error. Obviously, if I remove Redis and the adapter, it stops happening. Thank you very much for your help.

My code to start the server:

```
const http = require("http");
const express = require('express')
const app = express()
app.use(express.json({ limit: '1mb' }))
const server = http.createServer(app);
const { Server } = require("socket.io");
const { createAdapter } = require('@socket.io/redis-adapter');
const Redis = require('ioredis');

const pubClient = new Redis("Redis_url_here");
const subClient = pubClient.duplicate();

pubClient.on("error", logError);

subClient.on("error", logError);

const io = new Server(server);

io.adapter(createAdapter(pubClient, subClient));
server.listen(process.env.PORT || 3000, () => {
  if (process.send) process.send('ready');
  console.log('listening on port');
}).on('error', function (err) {
    console.log(err);
});
```

With this code the server works well and all the cluster are correctly connected via redis, but randomly have the crash ´read ECONNRESET´ :(

ioredis version: 5.3.2
redis version: 4.6.10
adapter version: 8.2.1
